Repository GoldKing9/airbnb_frontend, pull requests merged in 2023-08, with the labels that each got.

#13 [Feat] 검색 모달 병합
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/src/Header.tsx
  vite-project/src/SearchModal.tsx
  vite-project/src/datepicker-overrides.css
Labels: 전지희, 프론트엔드_구현

#9 [Feat] 회원가입 기능 구현
  vite-project/.eslintrc.cjs
  vite-project/index.html
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/setupProxy.js
  vite-project/src/App.tsx
  vite-project/src/Pages/Signup.tsx
  vite-project/src/index.css
  vite-project/src/main.tsx
Labels: 김형준, 프론트엔드_구현

#10 [Feat] 로그인 기능 구현
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/setupProxy.js
  vite-project/src/App.css
  vite-project/src/Pages/Signin.tsx
  vite-project/src/index.css
  vite-project/src/utils/Cookies.ts
Labels: 김형준, 프론트엔드_구현

#12 [Feat] 검색 모달 구현
  vite-project/package-lock.json
  vite-project/package.json
  vite-project/src/Header.tsx
  vite-project/src/SearchModal.tsx
  vite-project/src/datepicker-overrides.css
Labels: 전지희, 프론트엔드_구현

#17 [Feat] 프로필 페이지 1차 구현
  vite-project/package-lock.json
  vite-project/src/App.css
  vite-project/src/Pages/Profile.tsx
  vite-project/src/Utils/HostTab.tsx
  vite-project/src/Utils/StarRating.tsx
  vite-project/src/Utils/ToggleHandler.tsx
  vite-project/src/Utils/UserTab.tsx
  vite-project/src/components/Host.tsx
  vite-project/src/components/User.tsx
Labels: 김형준, 전지희, 프론트엔드_구현
